name: shoreline_monitor_wps
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pywps
  - flask
  - pandas
  - geopandas
  - python-dotenv
  - sqlalchemy
  - psycopg2-binary
  - plotly
  - nbformat
  - geopandas
  - holoviews
  - hvplot
  - colorcet
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - panel
  - geoviews

  - pip:
    - coastpy
